/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iota_iri_hash_PearlDiver */

#ifndef _Included_com_iota_iri_hash_PearlDiver
#define _Included_com_iota_iri_hash_PearlDiver
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iota_iri_hash_PearlDiver_TRANSACTION_LENGTH
#define com_iota_iri_hash_PearlDiver_TRANSACTION_LENGTH 8019L
#undef com_iota_iri_hash_PearlDiver_CURL_HASH_LENGTH
#define com_iota_iri_hash_PearlDiver_CURL_HASH_LENGTH 243L
#undef com_iota_iri_hash_PearlDiver_CURL_STATE_LENGTH
#define com_iota_iri_hash_PearlDiver_CURL_STATE_LENGTH 729L
#undef com_iota_iri_hash_PearlDiver_HIGH_BITS
#define com_iota_iri_hash_PearlDiver_HIGH_BITS -1LL
#undef com_iota_iri_hash_PearlDiver_LOW_BITS
#define com_iota_iri_hash_PearlDiver_LOW_BITS 0LL
/*
 * Class:     com_iota_iri_hash_PearlDiver
 * Method:    dcurl_init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_iota_iri_hash_PearlDiver_dcurl_1init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_iota_iri_hash_PearlDiver
 * Method:    dcurl_entry
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_iota_iri_hash_PearlDiver_dcurl_1entry
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_iota_iri_hash_PearlDiver
 * Method:    dcurl_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iota_iri_hash_PearlDiver_dcurl_1destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
