/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iota_iri_hash_PearlDiver */

#ifndef _Included_com_iota_iri_hash_PearlDiver
#define _Included_com_iota_iri_hash_PearlDiver
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iota_iri_hash_PearlDiver_TRANSACTION_LENGTH
#define com_iota_iri_hash_PearlDiver_TRANSACTION_LENGTH 8019L
#undef com_iota_iri_hash_PearlDiver_CURL_HASH_LENGTH
#define com_iota_iri_hash_PearlDiver_CURL_HASH_LENGTH 243L
#undef com_iota_iri_hash_PearlDiver_CURL_STATE_LENGTH
#define com_iota_iri_hash_PearlDiver_CURL_STATE_LENGTH 729L
#undef com_iota_iri_hash_PearlDiver_HIGH_BITS
#define com_iota_iri_hash_PearlDiver_HIGH_BITS -1LL
#undef com_iota_iri_hash_PearlDiver_LOW_BITS
#define com_iota_iri_hash_PearlDiver_LOW_BITS 0LL
/*
 * Class:     com_iota_iri_hash_PearlDiver
 * Method:    exlib_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_iota_iri_hash_PearlDiver_exlib_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_iota_iri_hash_PearlDiver
 * Method:    exlib_search
 * Signature: ([II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_iota_iri_hash_PearlDiver_exlib_1search
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_iota_iri_hash_PearlDiver
 * Method:    exlib_cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iota_iri_hash_PearlDiver_exlib_1cancel
  (JNIEnv *, jclass);

/*
 * Class:     com_iota_iri_hash_PearlDiver
 * Method:    exlib_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iota_iri_hash_PearlDiver_exlib_1destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_iota_iri_hash_PearlDiver_State */

#ifndef _Included_com_iota_iri_hash_PearlDiver_State
#define _Included_com_iota_iri_hash_PearlDiver_State
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
