/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_jni_dcurl */

#ifndef _Included_test_jni_dcurl
#define _Included_test_jni_dcurl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_jni_dcurl
 * Method:    dcurl_init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_test_1jni_1dcurl_dcurl_1init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     test_jni_dcurl
 * Method:    dcurl_entry
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_test_1jni_1dcurl_dcurl_1entry
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     test_jni_dcurl
 * Method:    dcurl_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_1jni_1dcurl_dcurl_1destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
