language: c

compiler:
  - gcc

before_install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y python3-pip
  - sudo apt-get install -y python3-cffi
  - sudo pip3 install --upgrade pip setuptools
  - sudo pip3 install --ignore-installed pyota

script:
  - make check
