/*
 * Copyright (C) 2018-2019 BiiLabs Co., Ltd. and Contributors
 * All Rights Reserved.
 * This is free software; you can redistribute it and/or modify it under the
 * terms of the MIT license. A copy of the license can be found in the file
 * "LICENSE" at the root of this distribution.
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define MIN_TRYTE_VALUE -13
#define MAX_TRYTE_VALUE 13
#define SIGNATURE_SIZE 6561
#define DEPTH 3
#define RADIX 3

#define HASH_TRYTES_LENGTH 81
#define NONCE_TRYTES_LENGTH 27
#define STATE_TRYTES_LENGTH 3 * HASH_TRYTES_LENGTH
#define TRANSACTION_TRYTES_LENGTH 2673

#define HASH_TRITS_LENGTH 243
#define NONCE_TRITS_LENGTH 81
#define STATE_TRITS_LENGTH 3 * HASH_TRITS_LENGTH
#define TRANSACTION_TRITS_LENGTH (TRANSACTION_TRYTES_LENGTH * 3)

#define SIGNATURE_MESSAGE_FRAGMENT_TRINARY_OFFSET 0
#define SIGNATURE_MESSAGE_FRAGMENT_TRINARY_SIZE 6561
#define ADDRESS_TRINARY_OFFSET                   \
    (SIGNATURE_MESSAGE_FRAGMENT_TRINARY_OFFSET + \
     SIGNATURE_MESSAGE_FRAGMENT_TRINARY_SIZE)
#define ADDRESS_TRINARY_SIZE 243
#define VALUE_TRINARY_OFFSET (ADDRESS_TRINARY_OFFSET + ADDRESS_TRINARY_SIZE)
#define VALUE_TRINARY_SIZE 81
#define OBSOLETE_TAG_TRINARY_OFFSET (VALUE_TRINARY_OFFSET + VALUE_TRINARY_SIZE)
#define OBSOLETE_TAG_TRINARY_SIZE 81
#define TIMESTAMP_TRINARY_OFFSET \
    (OBSOLETE_TAG_TRINARY_OFFSET + OBSOLETE_TAG_TRINARY_SIZE)
#define TIMESTAMP_TRINARY_SIZE 27
#define CURRENT_INDEX_TRINARY_OFFSET \
    (TIMESTAMP_TRINARY_OFFSET + TIMESTAMP_TRINARY_SIZE)
#define CURRENT_INDEX_TRINARY_SIZE 27
#define LAST_INDEX_TRINARY_OFFSET \
    (CURRENT_INDEX_TRINARY_OFFSET + CURRENT_INDEX_TRINARY_SIZE)
#define LAST_INDEX_TRINARY_SIZE 27
#define BUNDLE_TRINARY_OFFSET \
    (LAST_INDEX_TRINARY_OFFSET + LAST_INDEX_TRINARY_SIZE)
#define BUNDLE_TRINARY_SIZE 243
#define TRUNK_TRANSACTION_TRINARY_OFFSET \
    (BUNDLE_TRINARY_OFFSET + BUNDLE_TRINARY_SIZE)
#define TRUNK_TRANSACTION_TRINARY_SIZE 243
#define BRANCH_TRANSACTION_TRINARY_OFFSET \
    (TRUNK_TRANSACTION_TRINARY_OFFSET + TRUNK_TRANSACTION_TRINARY_SIZE)
#define BRANCH_TRANSACTION_TRINARY_SIZE 243
#define TAG_TRINARY_OFFSET \
    (BRANCH_TRANSACTION_TRINARY_OFFSET + BRANCH_TRANSACTION_TRINARY_SIZE)
#define TAG_TRINARY_SIZE 81
#define ATTACHMENT_TIMESTAMP_TRINARY_OFFSET \
    (TAG_TRINARY_OFFSET + TAG_TRINARY_SIZE)
#define ATTACHMENT_TIMESTAMP_TRINARY_SIZE 27

#define ATTACHMENT_TIMESTAMP_LOWER_BOUND_TRINARY_OFFSET \
    (ATTACHMENT_TIMESTAMP_TRINARY_OFFSET + ATTACHMENT_TIMESTAMP_TRINARY_SIZE)
#define ATTACHMENT_TIMESTAMP_LOWER_BOUND_TRINARY_SIZE 27
#define ATTACHMENT_TIMESTAMP_UPPER_BOUND_TRINARY_OFFSET \
    (ATTACHMENT_TIMESTAMP_LOWER_BOUND_TRINARY_OFFSET +  \
     ATTACHMENT_TIMESTAMP_LOWER_BOUND_TRINARY_SIZE)
#define ATTACHMENT_TIMESTAMP_UPPER_BOUND_TRINARY_SIZE 27
#define NONCE_TRINARY_OFFSET                           \
    (ATTACHMENT_TIMESTAMP_UPPER_BOUND_TRINARY_OFFSET + \
     ATTACHMENT_TIMESTAMP_UPPER_BOUND_TRINARY_SIZE)
#define NONCE_TRINARY_SIZE 81

#define TRANSACTION_TRINARY_SIZE                                               \
    (SIGNATURE_MESSAGE_FRAGMENT_TRINARY_SIZE + ADDRESS_TRINARY_SIZE +          \
     VALUE_TRINARY_SIZE + OBSOLETE_TAG_TRINARY_SIZE + TIMESTAMP_TRINARY_SIZE + \
     CURRENT_INDEX_TRINARY_SIZE + LAST_INDEX_TRINARY_SIZE +                    \
     BUNDLE_TRINARY_SIZE + TRUNK_TRANSACTION_TRINARY_SIZE +                    \
     BRANCH_TRANSACTION_TRINARY_SIZE + TAG_TRINARY_SIZE +                      \
     ATTACHMENT_TIMESTAMP_TRINARY_SIZE +                                       \
     ATTACHMENT_TIMESTAMP_LOWER_BOUND_TRINARY_SIZE +                           \
     ATTACHMENT_TIMESTAMP_UPPER_BOUND_TRINARY_SIZE + NONCE_TRINARY_SIZE)

extern char tryte_alphabet[];
extern const int indices[];

#endif
